name: MacOS Test
on:
  push:
    branches:
      - main
jobs:
  Build-MacOS:
    runs-on: macos-latest
    outputs:
      changelist: ${{ steps.build.outputs.changelist }}
      version: ${{ steps.build.outputs.version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CMake Build
        run: |
          mkdir cmake_build
          cd cmake_build
          cmake "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.13" -G "Xcode" ..

      - name: Build Project and Test
        run: |
          cd cmake_build
          cmake --build . --parallel
          ctest --output-on-failure

